#!/usr/bin/env python3
"""Publish the module tree and a discovery index from the framework manifests.

Each framework.toml is the source of truth. For every module we publish a
self-contained package under the path derived from its model's owl:Ontology IRI:

    /ns/framework/hipaa            -> (conneg) the model Turtle
    /ns/framework/hipaa.ttl        latest model
    /ns/framework/hipaa/1.0.0.ttl  immutable snapshot
    /ns/framework/hipaa/...        the full module (manifest + model + rules + constructs)

and a registry at /ns/index.json listing every module (name, version, IRI,
dependencies, source) so the site doubles as a package/discovery repository.

The index schema carries `maintainer` and `hosted` so community packages
(hosted in-tree under /ns/contrib/<handle>/<name>) and external packages
(indexed, hosted by the author) can be added later without schema changes.
"""
import argparse
import html
import json
import re
import shutil
import tomllib
from pathlib import Path

def _esc(s):
    return html.escape(str(s))


def write_netlify_config(out: Path, modules: list) -> None:
    """Generate _redirects + _headers so extensionless IRIs serve Turtle.

    Manifest-driven, so it scales to community modules automatically.
    """
    redirects = ["# generated by publish-vocab.py -- extensionless ontology IRI -> Turtle"]
    headers = ["# generated by publish-vocab.py", "/*", "  X-Content-Type-Options: nosniff", ""]
    for m in modules:
        rel = m["iri"][len(BASE):]                       # ns, ns/sdc, ns/framework/hipaa
        redirects.append(f"/{rel}  /{rel}.ttl  200")
        for path in (f"/{rel}", f"/{rel}.ttl", f"/{rel}/{m['version']}.ttl"):
            headers += [path, "  Content-Type: text/turtle; charset=utf-8", ""]
    (out / "_redirects").write_text("\n".join(redirects) + "\n", encoding="utf-8")
    (out / "_headers").write_text("\n".join(headers) + "\n", encoding="utf-8")


def write_registry_html(out: Path, modules: list) -> None:
    """Generate a static, browsable catalog page from the module list."""
    def render(m):
        rows = ""
        legal = m.get("legal")
        if legal:
            order = [("jurisdiction", "jurisdiction"), ("authority", "authority"),
                     ("instrument", "instrument"), ("interpretation", "interpretation"),
                     ("citation", "citation"), ("date", "date")]
            cells = "".join(
                f"<dt>{_esc(lbl)}</dt><dd>{_esc(legal[k])}</dd>"
                for k, lbl in order if legal.get(k))
            rows = f'<dl class="facets">{cells}</dl>'
        deps = (f'<div class="deps">depends on: {", ".join(_esc(d) for d in m["depends_on"])}</div>'
                if m.get("depends_on") else "")
        return (
            f'<div class="mod">'
            f'<div class="hd"><span class="name">{_esc(m["name"])}</span>'
            f'<span class="ver">{_esc(m["version"])}</span></div>'
            f'<div class="desc">{_esc(m["title"])}</div>'
            f'<div class="iri">{_esc(m["iri"])}</div>'
            f'{rows}{deps}'
            f'<div class="links">'
            f'<a href="{_esc(m["ttl"])}">RDF</a>'
            f'<a href="{_esc(m["manifest"])}">manifest</a>'
            f'<a href="{_esc(m["snapshot"])}">v{_esc(m["version"])}</a>'
            f'</div></div>'
        )

    core = [m for m in modules if m["type"] == "core"]
    frameworks = [m for m in modules if m["type"] != "core"]
    sections = ""
    if core:
        sections += "<h2>Core</h2>" + "".join(render(m) for m in core)
    if frameworks:
        sections += "<h2>Frameworks</h2>" + "".join(render(m) for m in frameworks)

    page = f"""<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Parajudica registry</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/style.css">
</head><body>
<main>
<h1>Registry</h1>
<nav class="topnav">
<a href="/">Home</a> &middot;
<a href="https://github.com/alfredr/parajudica">Code</a> &middot;
<a href="/ns">Vocabulary</a> &middot;
<a href="https://github.com/alfredr/parajudica/blob/main/CONTRIBUTING.md">Contribute</a> &middot;
<a href="https://doi.org/10.5281/zenodo.17825089">Archive</a>
</nav>
<p class="lede">Parajudica framework modules. Each resolves as RDF at its IRI; manifests and immutable version snapshots are linked. The full catalog is also available as <a href="/ns/index.json">index.json</a>. To add a module, see <a href="https://github.com/alfredr/parajudica/blob/main/CONTRIBUTING.md">Contributing</a>.</p>
{sections}
</main></body></html>
"""
    (out / "registry").mkdir(parents=True, exist_ok=True)
    (out / "registry" / "index.html").write_text(page, encoding="utf-8")

ROOT = Path(__file__).resolve().parent.parent
BASE = "https://parajudica.org/"
MANIFESTS = [
    "src/parajudica/metamodel/*/framework.toml",
    "examples/frameworks/*/framework.toml",
]
ONTOLOGY = re.compile(r"<(https://parajudica\.org/[^>#]+)>\s+a\s+owl:Ontology")
TITLE = re.compile(r'dcterms:title\s+"([^"]+)"')
VERSIONINFO = re.compile(r'owl:versionInfo\s+"([^"]+)"')


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=str(ROOT / "site" / "public"))
    out = Path(ap.parse_args().out)

    modules = []
    for glob in MANIFESTS:
        for manifest in sorted(ROOT.glob(glob)):
            mod_dir = manifest.parent
            man = tomllib.loads(manifest.read_text(encoding="utf-8"))
            version = man.get("version", "0.0.0")
            model_rel = man.get("files", {}).get("model", [None])[0]
            if not model_rel:
                continue
            text = (mod_dir / model_rel).read_text(encoding="utf-8")
            vinfo = VERSIONINFO.search(text)
            if vinfo and vinfo.group(1) != version:
                raise SystemExit(
                    f"version drift: {manifest} declares version {version!r} but "
                    f"{model_rel} has owl:versionInfo {vinfo.group(1)!r} -- keep them in sync"
                )
            m = ONTOLOGY.search(text)
            if not m:
                print(f"  WARN {mod_dir/model_rel}: no owl:Ontology header, skipped")
                continue
            iri = m.group(1)
            rel = iri[len(BASE):]                       # ns, ns/sdc, ns/framework/hipaa

            # full package: copy the whole module dir under its path
            pkg = out / rel
            if pkg.exists():
                shutil.rmtree(pkg)
            shutil.copytree(mod_dir, pkg)
            # dereference target for the IRI, plus an immutable snapshot
            (out / f"{rel}.ttl").parent.mkdir(parents=True, exist_ok=True)
            (out / f"{rel}.ttl").write_text(text, encoding="utf-8")
            (pkg / f"{version}.ttl").write_text(text, encoding="utf-8")

            title_m = TITLE.search(text)
            entry = {
                "name": man.get("name"),
                "title": title_m.group(1) if title_m else man.get("description", ""),
                "version": version,
                "type": man.get("type", "framework"),
                "maintainer": "parajudica",
                "hosted": True,
                "iri": iri,                              # absolute canonical identifier
                # fetch/nav paths are root-relative so they resolve on any host
                # (localhost, *.netlify.app, a deploy preview, or parajudica.org)
                "ttl": f"/{rel}",                        # dereferences to the model
                "snapshot": f"/{rel}/{version}.ttl",
                "manifest": f"/{rel}/framework.toml",
                "depends_on": man.get("depends_on", []),
            }
            if man.get("legal"):                         # structured legal citation
                entry["legal"] = man["legal"]
            modules.append(entry)

    index = {
        "registry": "parajudica",
        "base": BASE.rstrip("/"),
        "modules": sorted(modules, key=lambda e: (e["type"] != "core", e["name"])),
    }
    (out / "ns").mkdir(parents=True, exist_ok=True)
    (out / "ns" / "index.json").write_text(json.dumps(index, indent=2) + "\n", encoding="utf-8")
    write_registry_html(out, index["modules"])
    write_netlify_config(out, index["modules"])

    for e in index["modules"]:
        dep = f"  deps={e['depends_on']}" if e["depends_on"] else ""
        print(f"  {e['name']:8} {e['version']}  {e['type']:8} -> /{e['iri'][len(BASE):]}{dep}")
    print(f"published {len(modules)} modules + /ns/index.json -> {out}")


if __name__ == "__main__":
    main()
